/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAppRouteRouteImport } from './routes/_authenticated/_app/route'
import { Route as AuthenticatedAppTasksRouteImport } from './routes/_authenticated/_app/tasks'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppResearchRouteImport } from './routes/_authenticated/_app/research'
import { Route as AuthenticatedAppMeetingsRouteImport } from './routes/_authenticated/_app/meetings'
import { Route as AuthenticatedAppEmailRouteImport } from './routes/_authenticated/_app/email'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/_app/chat'
import { Route as AuthenticatedAppChatIndexRouteImport } from './routes/_authenticated/_app/chat/index'
import { Route as AuthenticatedAppChatThreadIdRouteImport } from './routes/_authenticated/_app/chat/$threadId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTasksRoute = AuthenticatedAppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppResearchRoute =
  AuthenticatedAppResearchRouteImport.update({
    id: '/research',
    path: '/research',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppMeetingsRoute =
  AuthenticatedAppMeetingsRouteImport.update({
    id: '/meetings',
    path: '/meetings',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppEmailRoute = AuthenticatedAppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRouteRoute,
} as any)
const AuthenticatedAppChatIndexRoute =
  AuthenticatedAppChatIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)
const AuthenticatedAppChatThreadIdRoute =
  AuthenticatedAppChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAppChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/email': typeof AuthenticatedAppEmailRoute
  '/meetings': typeof AuthenticatedAppMeetingsRoute
  '/research': typeof AuthenticatedAppResearchRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/tasks': typeof AuthenticatedAppTasksRoute
  '/chat/$threadId': typeof AuthenticatedAppChatThreadIdRoute
  '/chat/': typeof AuthenticatedAppChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/email': typeof AuthenticatedAppEmailRoute
  '/meetings': typeof AuthenticatedAppMeetingsRoute
  '/research': typeof AuthenticatedAppResearchRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/tasks': typeof AuthenticatedAppTasksRoute
  '/chat/$threadId': typeof AuthenticatedAppChatThreadIdRoute
  '/chat': typeof AuthenticatedAppChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_app': typeof AuthenticatedAppRouteRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/_app/chat': typeof AuthenticatedAppChatRouteWithChildren
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/email': typeof AuthenticatedAppEmailRoute
  '/_authenticated/_app/meetings': typeof AuthenticatedAppMeetingsRoute
  '/_authenticated/_app/research': typeof AuthenticatedAppResearchRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/_app/tasks': typeof AuthenticatedAppTasksRoute
  '/_authenticated/_app/chat/$threadId': typeof AuthenticatedAppChatThreadIdRoute
  '/_authenticated/_app/chat/': typeof AuthenticatedAppChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/chat'
    | '/dashboard'
    | '/email'
    | '/meetings'
    | '/research'
    | '/settings'
    | '/tasks'
    | '/chat/$threadId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/dashboard'
    | '/email'
    | '/meetings'
    | '/research'
    | '/settings'
    | '/tasks'
    | '/chat/$threadId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_app'
    | '/api/chat'
    | '/_authenticated/_app/chat'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/email'
    | '/_authenticated/_app/meetings'
    | '/_authenticated/_app/research'
    | '/_authenticated/_app/settings'
    | '/_authenticated/_app/tasks'
    | '/_authenticated/_app/chat/$threadId'
    | '/_authenticated/_app/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/tasks': {
      id: '/_authenticated/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedAppTasksRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/research': {
      id: '/_authenticated/_app/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedAppResearchRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/meetings': {
      id: '/_authenticated/_app/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedAppMeetingsRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/email': {
      id: '/_authenticated/_app/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof AuthenticatedAppEmailRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/chat': {
      id: '/_authenticated/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/_app/chat/': {
      id: '/_authenticated/_app/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedAppChatIndexRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
    '/_authenticated/_app/chat/$threadId': {
      id: '/_authenticated/_app/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedAppChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedAppChatRoute
    }
  }
}

interface AuthenticatedAppChatRouteChildren {
  AuthenticatedAppChatThreadIdRoute: typeof AuthenticatedAppChatThreadIdRoute
  AuthenticatedAppChatIndexRoute: typeof AuthenticatedAppChatIndexRoute
}

const AuthenticatedAppChatRouteChildren: AuthenticatedAppChatRouteChildren = {
  AuthenticatedAppChatThreadIdRoute: AuthenticatedAppChatThreadIdRoute,
  AuthenticatedAppChatIndexRoute: AuthenticatedAppChatIndexRoute,
}

const AuthenticatedAppChatRouteWithChildren =
  AuthenticatedAppChatRoute._addFileChildren(AuthenticatedAppChatRouteChildren)

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRouteWithChildren
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppEmailRoute: typeof AuthenticatedAppEmailRoute
  AuthenticatedAppMeetingsRoute: typeof AuthenticatedAppMeetingsRoute
  AuthenticatedAppResearchRoute: typeof AuthenticatedAppResearchRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTasksRoute: typeof AuthenticatedAppTasksRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppChatRoute: AuthenticatedAppChatRouteWithChildren,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppEmailRoute: AuthenticatedAppEmailRoute,
  AuthenticatedAppMeetingsRoute: AuthenticatedAppMeetingsRoute,
  AuthenticatedAppResearchRoute: AuthenticatedAppResearchRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTasksRoute: AuthenticatedAppTasksRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
